# Generated by Django 3.1.6 on 2021-02-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='phtoto_author',
            new_name='photo_author',
        ),
    ]
