# Generated by Django 3.1.6 on 2021-02-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0002_auto_20210204_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
